version: '3.7'
x-common_variables:
  &services_hosts
  TEST_HOST: 172.20.0.3

  RABBITMQ_SERVICE_HOST: 172.20.0.16
  RABBITMQ_SERVICE_PORT: 5672

  RIAK_SERVICE_HOST: 172.20.0.17
  RIAK_SERVICE_PORT: 8087 

  REDIS_SERVICE_HOST: 172.20.0.18
  REDIS_SERVICE_PORT: 6379

  CLICKHOUSE_SERVICE_CLUSTER: 172.20.0.22:8123
  CLICKHOUSE_SERVICE_DATABASE: "reviews"
  CLICKHOUSE_SERVICE_USERNAME: "review"
  CLICKHOUSE_SERVICE_PASSWORD: "password"

  REDPANDA_SERVICE_HOST: 172.20.0.28

services:

  test:
    image: demo 
    hostname: test
    container_name: test
    ports:
      - 8089:8080 # forward graffQL
      - 4000:4000 # dev
    stdin_open: true
    tty: true
    user: ${U_ID}:${U_ID}
    environment: *services_hosts
    working_dir: /opt/app/
    volumes:
      - ${HOME}/projects/interview:/opt/interview
      - ${HOME}/projects/next/:/opt/app/
      - ${HOME}/.cache:${HOME}/.cache
      - ./rebuild_start_in_docker.sh:/opt/app/rebuild_start_in_docker.sh
      - ./start-in-docker:/opt/app/start-in-docker
      - ./start-io:/opt/app/start-io
      - ${HOME}/.ssh:${HOME}/.ssh:ro
      # - ${HOME}/.mix:${HOME}/.mix
      # - ${HOME}/.hex:${HOME}/.hex
      - ${HOME}/.bashrc:${HOME}/.bashrc:ro
      - ${HOME}/.bash_profile:${HOME}/.bash_profile:ro
      - ${HOME}/.bash_aliases:${HOME}/.bash_aliases:ro
    command: bash
    networks:
      backend:
        ipv4_address: 172.20.0.3

  rabbit:
    image: rabbit-next
    hostname: rabbit
    container_name: rabbit
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      backend:
        ipv4_address: 172.20.0.16

  riak:
    image: riak-leveldb
    hostname: riak
    container_name: riak
    ports:
      - 8087:8087
      - 8098:8098
    networks:
      backend:
        ipv4_address: 172.20.0.17
    volumes:
      - riak-data:/riak-data # leveldb.data_root

  redis:
    image: redis
    hostname: redis
    container_name: redis
    # command: redis-server --requirepass next
    ports:
      - 6379:6379
    networks:
      backend:
        ipv4_address: 172.20.0.18

  clickhouse:
    image: yandex/clickhouse-server
    hostname: clickhouse
    container_name: clickhouse
    environment:
     - CLICKHOUSE_DB=reviews
     - CLICKHOUSE_USER=review
     - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
     - CLICKHOUSE_PASSWORD=password
    volumes:
      - ../../ratings/ddl:/root/ddl
      - ../../ratings/var/lib/clickhouse/user_files:/var/lib/clickhouse/user_files
      - clickhouse-data:/var/lib/clickhouse
      - ../../ratings/etc/clickhouse-server/users.d/review.xml:/etc/clickhouse-server/users.d/review.xml
      - ../../ratings/etc/clickhouse-server/config.d/rabbit.xml:/etc/clickhouse-server/config.d/rabbit.xml
    ports:
      - 8123:8123
    ulimits:
      nofile: 262144
    networks:
      backend:
        ipv4_address: 172.20.0.22
 
  postgres:
    image: bitnami/postgresql
    hostname: postgres
    container_name: postgres
    stdin_open: true
    tty: true
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRESQL_DATABASE: cache_layer
    volumes:
      - postgres_data:/bitnami/postgresql
    networks:
      backend:
        ipv4_address: 172.20.0.26

  redpanda:
    command:
    - redpanda
    - start
    - --smp
    - '1'
    - --reserve-memory
    - 0M
    - --overprovisioned
    - --node-id
    - '0'
    - --kafka-addr
    - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
    - --advertise-kafka-addr
    - PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
    image: docker.vectorized.io/vectorized/redpanda:latest
    container_name: redpanda
    hostname: redpanda
    ports:
    - 9092:9092
    - 29092:29092
    networks:
      backend:
        ipv4_address: 172.20.0.28

networks:
  backend:
    ipam:
      config:
        - subnet: 172.20.0.0/24

volumes:
  riak-data:
  etcd-vol:
  clickhouse-data:
  postgres_data:
